language: rust
rust: [stable, beta, nightly]
cache: cargo
script:
  - cargo build --all
  - PS_LOCAL_RUNTIME=1 cargo run plugin-system-example
  - cargo build --all --release
  - PS_LOCAL_RUNTIME=1 cargo run plugin-system-example --release
